### ISSUE TITLE
Невозможно напечатать

### ISSUE THREAD

**Issue by dodo325** [codup/odoo-ru#6]
Строка:
https://github.com/codup/odoo-ru/blob/a4c29c5b81e0ea654f74cfc7ea11995a4a66f387/l10n_ru_doc/account_invoice.py#L43

Вызывает ошибку, при попытки печяти оферты:
```python
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/addons/web/controllers/main.py", line 935, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/addons/web/controllers/main.py", line 923, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/addons/l10n_ru_doc/sale.py", line 17, in print_quotation
    return self.env['report'].get_action(self, 'l10n_ru_doc.report_order')
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/api.py", line 760, in __getitem__
    return self.registry[model_name]._browse((), self)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180718-py3.6.egg/odoo/modules/registry.py", line 179, in __getitem__
    return self.models[model_name]
KeyError: 'report'
```

**Comment by wowas18** [comment]
For Odoo11 try [download last version](https://www.odoo.com/apps/modules/11.0/l10n_ru_doc/).
And install it on new DB.
